# == This file defines the page layouts for new pages.
#
# For further information please see https://guides.alchemy-cms.com/pages.html

- name: index
  unique: true
  elements:
    - article
    - header_contact
    - carousel_slide
    - promo_card
    - product_card
  autogenerate:
    - header_contact

- name: standard
  unique: false
  elements:
    - article
  autogenerate:
    - article

- name: products
  unique: true
  elements:
    - product_card

- name: global_layout
  unique: true
  layoutpage: true
  elements:
    - header_contact
  autogenerate:
    - header_contact



