test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: S3
  access_key_id: <%= ENV.fetch('R2_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('R2_SECRET_ACCESS_KEY') %>
  region: <%= ENV.fetch('R2_REGION') %>
  bucket: <%= ENV.fetch('R2_BUCKET') %>
  endpoint: <%= ENV.fetch('R2_ENDPOINT') %>
  compute_checksums: false
  force_path_style: true
