# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Spree::Core::Engine.load_seed
Spree::Auth::Engine.load_seed


# ==========================================
# DigitalMonkeyDeals Categories Seed Data
# Generated at 2026-05-22 08:03:27 +0000
# ==========================================

puts "Loading Category Taxons..."
categories_taxonomy = Spree::Taxonomy.find_or_create_by!(name: "Categories")
categories_root = categories_taxonomy.root

# Clear existing children for clean run
categories_root.children.destroy_all

monkey_categories = [
  "Acrylic Awards",
  "Acrylic Displays",
  "Acrylic Sign Holders",
  "Adapters & Chargers & Cables",
  "Address Books",
  "Adhesive Calendars",
  "Adhesive Note Pads",
  "Adhesives",
  "Advertisements",
  "Air Fresheners",
  "Airline Accessories",
  "Alarm Clocks",
  "Alarms and Protective Devices",
  "Albums",
  "Almanacs",
  "Alumni Items",
  "Analog Clocks",
  "Analog Watches",
  "Animal Theme Products",
  "Animals - Stuffed",
  "Antenna Accessories",
  "Anti-Bacterial",
  "Apparel - Athletic",
  "Apparel - Bed and Bath",
  "Apparel - Boy's",
  "Apparel - Children's",
  "Apparel - Girl's",
  "Apparel - Golf",
  "Apparel - Men's",
  "Apparel - Unisex",
  "Apparel - Warehouse",
  "Apparel - Women's",
  "Appliques and Embroidery",
  "Appointment Accessories",
  "Aprons",
  "Aquatics",
  "Arm Bands",
  "Aromatherapy",
  "Art and Craft Supplies",
  "Ashtrays",
  "Audio Products",
  "Auto Accessories",
  "Award Certificates",
  "Awards/Award Programs",
  "Awnings",
  "Baby Items",
  "Back Braces",
  "Backpacks",
  "Backscratchers",
  "Badge Accessories",
  "Badge Holders",
  "Badges",
  "Bag Accessories",
  "Bag and Box Sealers",
  "Bags - Club/Travel",
  "Bags - Cotton",
  "Bags - Drawstring",
  "Bags - Duffel",
  "Bags - Gift",
  "Bags - Insulated",
  "Bags - Jute",
  "Bags - Laptop/Computer",
  "Bags - Litter",
  "Bags - Lunch",
  "Bags - Merchandise",
  "Bags - Paper",
  "Bags - Plastic",
  "Bags - Saddle",
  "Bags - Tote",
  "Balloon Accessories",
  "Balloons",
  "Ballpoint Pens",
  "Balls",
  "Bandages",
  "Bandannas",
  "Bands",
  "Bank Accessories",
  "Bank Bags and Envelopes",
  "Banks-Savings",
  "Banner and Pennant Accessories",
  "Banners",
  "Bar Accessories",
  "Barbeque Accessories",
  "Barrettes",
  "Barware",
  "Baseball and Softball Products",
  "Bases",
  "Basketball Sets",
  "Baskets",
  "Bathrobes",
  "Bathroom Accessories",
  "Batteries",
  "Battery-operated Products",
  "Beach Accessories",
  "Beauty Aids and Health Products",
  "Bedding",
  "Beer Accessories",
  "Bell Pulls",
  "Bells",
  "Belt Buckles",
  "Belts",
  "Beverage - Private Label",
  "Beverage Accessories",
  "Beverage Containers",
  "Beverage Holders-Insulated",
  "Bibs",
  "Bicycle Accessories",
  "Bicycles",
  "Billboards",
  "Binders",
  "Binoculars",
  "Bird Feeders",
  "Blankets",
  "Blazers",
  "Blouses",
  "Bluetooth",
  "Board Games",
  "Boating Accessories",
  "Boats",
  "Bobble Heads",
  "Book Accessories",
  "Bookmarks",
  "Books - General",
  "Bottle Stoppers",
  "Bottle and Can Openers",
  "Bottled Waters",
  "Bottles",
  "Bottles - Straps and Holders",
  "Bowls",
  "Box Accessories",
  "Box Cutters",
  "Boxes",
  "Bracelets",
  "Breath Mints",
  "Breathlyzer",
  "Briefcases and Attaches",
  "Brushes and Brooms",
  "Buckets",
  "Bulletin Boards",
  "Bumper Stickers",
  "Business Card Accessories",
  "Business Card Holders",
  "Business Cards",
  "Business Meeting Products",
  "Buttons",
  "CD Cases",
  "CD Packaging",
  "CD's",
  "Calculators",
  "Calendar Accessories",
  "Calendar Pads",
  "Calendars",
  "Camera Cases",
  "Cameras",
  "Camp Shirts",
  "Camping Equipment and Accessories",
  "Can Accessories",
  "Candles and Candle Holders",
  "Candy",
  "Candy - Custom",
  "Candy - Individually Wrapped",
  "Candy/Cookie Containers",
  "Canisters",
  "Canopies",
  "Cans",
  "Canteens",
  "Canvas",
  "Cap Accessories",
  "Caps and Hats",
  "Carabiners",
  "Carafes",
  "Cards",
  "Cases",
  "Casino Accessories",
  "Cassette Holders",
  "Cast Products",
  "Cell Phone Accessories",
  "Ceramic Spec-Custom Made",
  "Chairs",
  "Chalk Boards",
  "Chalk and Crayons",
  "Chamois",
  "Champagne Accessories",
  "Champagne Glasses",
  "Characters",
  "Charms",
  "Charts and Graphs",
  "Checkbook Covers",
  "Cheering Accessories",
  "Cheese and Meat Products",
  "Chefwear",
  "Chests",
  "Chewing Gum",
  "Child Accessories",
  "Chimes",
  "Chocolate",
  "Chocolate - Custom",
  "Christmas Accessories",
  "Cigar Accessories",
  "Cigars and Cigarettes",
  "Clapboards",
  "Cleaners",
  "Clip-on Products",
  "Clipboards",
  "Clips - Bag",
  "Clips - Money",
  "Clips - Paper / Memo",
  "Clock Radios",
  "Clocks",
  "Closeouts",
  "Coasters",
  "Coats",
  "Cocktail Picks / Forks",
  "Coffee Accessories",
  "Coffee Makers",
  "Coffee or Cocoa or Tea",
  "Coin Pouches",
  "Coins",
  "Collectibles",
  "Colognes",
  "Coloring Accessories",
  "Combs",
  "Commemorative Products",
  "Compact Disc Holders",
  "Compasses",
  "Compressors",
  "Computer Accessories",
  "Computer Software",
  "Computers",
  "Condoms",
  "Confetti",
  "Construction Accessories",
  "Converters",
  "Cookbooks",
  "Cookies",
  "Cooking Accessories",
  "Coolers",
  "Cork Boards",
  "Corks",
  "Corkscrews",
  "Correspondence Products",
  "Cosmetic Organizers",
  "Costumes and Accessories",
  "Cots",
  "Coupon Accessories",
  "Covers",
  "Cowbells",
  "Crafts",
  "Crayons",
  "Credit Card Accessories",
  "Crowns",
  "Crystal Pens",
  "Crystal Products",
  "Cuff Accessories",
  "Cups",
  "Currency Accessories",
  "Curtains",
  "Custom Products",
  "Cutting Boards",
  "Cutting Products",
  "DVD Packaging",
  "Dart Boards",
  "Decals",
  "Decanters",
  "Decorations",
  "Dental Accessories",
  "Dental Floss",
  "Desk Accessories",
  "Desk Calendars",
  "Desk Clocks",
  "Desk Nameplates",
  "Desk Pads",
  "Desk Sets",
  "Desk Tools",
  "Desserts",
  "Diaries - Desk",
  "Dice",
  "Digital Clocks",
  "Digital Frame",
  "Digital Watches",
  "Dining Accessories",
  "Diploma Covers",
  "Direct Mail Items",
  "Dishes",
  "Dispensers",
  "Display Products",
  "Disposable Products",
  "Diving Equipment",
  "Doctor Accessories",
  "Document Accessories",
  "Dog Collar",
  "Dog Tags",
  "Dolls",
  "Door Hangers",
  "Door Stops",
  "Doormats",
  "Dress Clothes",
  "Dress Shirts",
  "Dresses and Skirts",
  "Drinkware",
  "Dry Erase Boards",
  "Dryers",
  "Ear Accessories",
  "Ear Plugs",
  "Earbuds",
  "Earmuffs and Headbands",
  "Easels",
  "Educational Products",
  "Electric Current Accessories",
  "Electric Outlet Protectors",
  "Electronic Device Skins",
  "Electronic Devices",
  "Emblems",
  "Embroidery",
  "Emergency Accessories",
  "Emery Boards",
  "Envelopes",
  "Environmental Products",
  "Erasers",
  "Executive Gifts",
  "Exercise Accessories",
  "Exterior Literature Holders",
  "Eye Accessories",
  "Eyeglass Accessories",
  "Eyeglass Cases and Accessories",
  "Eyeglasses - Safety",
  "Fabrics - Non-Wearables",
  "Facility Signs and Wayfinding",
  "Fanny Packs",
  "Fans",
  "Farm Themed",
  "File Card Holders",
  "Files",
  "Fingernail Accessories",
  "Fire Accessories",
  "Fire Extinguishers",
  "Firearms",
  "First Aid Kits",
  "Fishing Accessories",
  "Fitness Accessories",
  "Flagpoles",
  "Flags/Flag Accessories",
  "Flame Resistant",
  "Flash Drives",
  "Flashlights",
  "Flasks",
  "Fleece",
  "Flip Flops",
  "Floor Mats",
  "Flotation Devices",
  "Flowers",
  "Fly Swatters",
  "Flyers",
  "Flying Saucers and Discs",
  "Foam Novelties",
  "Folders",
  "Folding Products",
  "Food Gifts",
  "Food Safe Packaging/Boxes",
  "Food and Beverage Products",
  "Football Accessories",
  "Formalwear",
  "Framed Products",
  "Frisbees",
  "Fruits",
  "Fulfillment Programs",
  "Fun Products",
  "Fund Raising",
  "Funnels",
  "Furnishings",
  "Furniture",
  "Furry Creatures",
  "GPS Accessories",
  "Gambling Accessories",
  "Games - Board",
  "Games - Miscellaneous",
  "Gaming Products",
  "Garden Accessories",
  "Garters",
  "Gauges",
  "Gavels",
  "Gel Pens",
  "Gift Accessories",
  "Gift Baskets",
  "Gift Box",
  "Gift Cards",
  "Gifts",
  "Glass Specialties-Custom Made",
  "Glasses-Drinking",
  "Glasses-Eye",
  "Globes",
  "Gloves",
  "Goggles",
  "Golf Accessories",
  "Golf Balls",
  "Golf Clubs",
  "Golf Tees",
  "Gourmet Foods",
  "Gowns",
  "Graduation",
  "Greens / Grass",
  "Greeting and Thank-you Cards",
  "Grills",
  "Growth Aids",
  "Guards",
  "Guides",
  "Hair Accessories",
  "Hair Care",
  "Halloween Accessories",
  "Hammocks",
  "Hand Fans",
  "Hand Sanitizers",
  "Handcuffs",
  "Handkerchiefs",
  "Hangers",
  "Hanging Products",
  "Hardware",
  "Hats",
  "Headbands",
  "Headphones",
  "Health Accessories",
  "Health and Beauty Aids",
  "Heat Accessories",
  "Heat Packs",
  "Heat Transfers",
  "Highlighters",
  "Hobbies and Crafts",
  "Hockey Accessories",
  "Hockey Pucks",
  "Hole Punches",
  "Holiday Gifts",
  "Holiday Goods",
  "Hollywood",
  "Horns",
  "Hosiery",
  "Hot Sauce",
  "Hourglasses",
  "Hunting Accessories",
  "Hydration Backpack",
  "ID Holders",
  "Ice Buckets and Accessories",
  "Ice Packs",
  "Ice Scrapers",
  "Incense",
  "Incentive Programs",
  "Index Cards",
  "Inflatables",
  "Ink-Stamp Pads",
  "Insect Repellent",
  "Insulated Products",
  "Invitations",
  "Irons",
  "Jackets",
  "Jar Openers",
  "Jars",
  "Jewelry",
  "Jewelry - Rings",
  "Jewelry Accessories",
  "Jewelry Boxes",
  "Jogging and Running Accessories",
  "Journals",
  "Jugs",
  "Kaleidoscope",
  "Key Accessories",
  "Key Blanks",
  "Key Cards",
  "Key Cases",
  "Key Chains / Rings / Tags",
  "Key Holders",
  "Keys",
  "Kids/Children's Products",
  "Kitchen Accessories",
  "Kitchen Appliances",
  "Kitchen Utensils",
  "Kites",
  "Kits-Automotive",
  "Kits-Makeup",
  "Kits-Other",
  "Kits-Survival",
  "Kits-Travel",
  "Knee Pads",
  "Knives/Knife Accessories",
  "Labels and Label Accessories",
  "Laminated Products",
  "Laminating Machines and Supplies",
  "Lamps",
  "Lanterns",
  "Lanyards",
  "Lapel Pins",
  "Laptop Accessories",
  "Laser Pointers",
  "Laundry Accessories",
  "Lawn and Garden Accessories",
  "Leashes",
  "Leather Specialties",
  "Legal Accessories",
  "Leis",
  "Leisure Products",
  "Letter Openers",
  "Levels",
  "Library Accessories",
  "License Plates and Frames",
  "Lids",
  "Light Bulbs",
  "Light-Up Products",
  "Lighters",
  "Lighting Products",
  "Lights",
  "Lint Brush/Roller",
  "Lip Balm",
  "Liquor Accessories",
  "Liquor Glasses",
  "Literature / Brochure Holders",
  "Locks",
  "Lotion",
  "Lottery Accessories",
  "Loyalty Cards",
  "Luggage",
  "Luggage Tags",
  "Lunch Boxes/Kits",
  "Lures",
  "MP3 Players",
  "Magnetic Accessories",
  "Magnets",
  "Magnifiers",
  "Mailboxes",
  "Mailers",
  "Mailing Accessories",
  "Makeup and Accessories",
  "Manicure Kits/Accessories",
  "Map Cases and Holders",
  "Marble Products",
  "Markers",
  "Mascots",
  "Masks",
  "Massagers",
  "Matches",
  "Mats - Auto",
  "Mats - Counter",
  "Measuring Devices",
  "Medallions",
  "Medals",
  "Medical Exam Gloves",
  "Medical Products",
  "Medicine",
  "Megaphones",
  "Membership Accessories",
  "Memo Accessories",
  "Memo Boards",
  "Memo Books",
  "Memo Pad and Paper Holders",
  "Memo Pads and Cubes",
  "Men's Jewelry",
  "Men's Watches",
  "Menus and Menu Covers",
  "Merchandise Displays",
  "Message Accessories",
  "Messenger Bags",
  "Metal Specialties",
  "Metric Accessories",
  "Microscopes",
  "Miniatures and Replicas",
  "Mint Tins",
  "Mints",
  "Mirrors",
  "Miscellaneous",
  "Mittens",
  "Mitts",
  "Mobiles",
  "Models",
  "Money",
  "Money Accessories",
  "Money-Play",
  "Monitor Frames",
  "Monoculars",
  "Motorcycle",
  "Mouse Pads",
  "Mouse-Computer",
  "Mugs and Steins",
  "Multifunction Tools",
  "Multisheet Calendars",
  "Murals",
  "Musical Instruments",
  "Musical Specialties",
  "Nail Clippers",
  "Nail Polish",
  "Nail files",
  "Nails",
  "Name Badges and Accessories",
  "Nameplates",
  "Napkin Rings",
  "Napkins",
  "Neck Accessories",
  "Necklaces",
  "Neckties",
  "Neckwear",
  "Night Lights",
  "Noisemakers",
  "Note Accessories",
  "Note Pads",
  "Notebooks",
  "Novelties",
  "Nutrition Items",
  "Nuts",
  "Office Supplies",
  "Openers - Bags",
  "Openers - Letter",
  "Optical Goods",
  "Organic",
  "Organizers",
  "Ornaments",
  "Outdoor Accessories",
  "Outerwear",
  "Oven Mitts/Pot Holders",
  "Overalls",
  "Pacifiers",
  "Packaging",
  "Padfolios",
  "Pads",
  "Pails",
  "Paint Accessories",
  "Paintings",
  "Pajamas",
  "Palettes",
  "Pans",
  "Pants",
  "Paper Dispensers",
  "Paper Holders",
  "Paper Rolls",
  "Paper Specialties-Stock and Custom",
  "Paperweights",
  "Parade Accessories",
  "Parking Accessories",
  "Party Favors",
  "Party Supplies",
  "Passport Accessories",
  "Patches",
  "Patriotic",
  "Pedometers",
  "Peel and Stick Calendars",
  "Pen Holders",
  "Pen Sets",
  "Pen and Pencil Accessories",
  "Pen and Pencil Holders",
  "Pen and Pencil Sets",
  "Pencil Sharpeners",
  "Pencils",
  "Pendants",
  "Pennants",
  "Pens",
  "Pepper Spray",
  "Perfume",
  "Permits",
  "Perpetual Calendars",
  "Personal Care Items",
  "Pet Accessories",
  "Pharmaceutical Accessories",
  "Phone Accessories",
  "Phone Books",
  "Phone Calling Cards",
  "Photo Albums",
  "Photo ID's",
  "Photography Accessories",
  "Physical Therapy Products",
  "Picnic Accessories",
  "Picture/Photo Frames",
  "Pictures and Paintings",
  "Pill Box",
  "Pillows",
  "Pins",
  "Pitchers",
  "Placemats",
  "Planners / Organizers",
  "Plants",
  "Plaques",
  "Plastic Cups",
  "Plastic Labels",
  "Plates and Platters",
  "Playing Cards and Accessories",
  "Plugs",
  "Plush",
  "Pocket Knives",
  "Pocket Protectors",
  "Pockets",
  "Point of Purchase",
  "Poker Accessories",
  "Polishers and  Dusters",
  "Polos or Knit",
  "Pom Poms",
  "Ponchos",
  "Pool Accessories",
  "Popcorn",
  "Portable Accessories",
  "Portfolios",
  "Post Cards",
  "Poster Stands",
  "Posters",
  "Pots",
  "Pouches",
  "Power Banks",
  "Power Supplies / Inverters",
  "Presentation Accessories",
  "Presentation Folders",
  "Print Accessories",
  "Printers / PC",
  "Projectors",
  "Promotions",
  "Protective Devices",
  "Pullovers",
  "Pumps",
  "Puppets",
  "Purifiers",
  "Purses",
  "Putters",
  "Puzzles and Games",
  "Rackets",
  "Racks and Holders",
  "Radios",
  "Rain Accessories",
  "Rain Gauges",
  "Rainwear",
  "Razors",
  "Reading Accessories",
  "Recognition Products",
  "Record Players / Turntables",
  "Recorders",
  "Recreation Accessories",
  "Recycled Products",
  "Reels",
  "Reflectors",
  "Refrigerators",
  "Religious Goods",
  "Remote Controls",
  "Restaurant Accessories",
  "Restaurant Items",
  "Retail Accessories",
  "Ribbons",
  "Ring Binders",
  "Rings",
  "Road Accessories",
  "Rocks",
  "Roller Ball Pens",
  "Ropes",
  "Rubber Bands",
  "Rubber Ducks",
  "Rugs",
  "Rulers",
  "Safes",
  "Safety Accessories",
  "Safety Products",
  "Safety Recognition",
  "Salt and Pepper Shakers",
  "Sampler Paddles",
  "Sashes",
  "Scales",
  "Scanners - PC",
  "Scarves",
  "Scented Products",
  "School Spirit",
  "School Supplies",
  "Scissors",
  "Scrapers",
  "Scratch-Off Items",
  "Screen Cleaners",
  "Screen Printing Services",
  "Screwdrivers",
  "Scrubs",
  "Sculptures",
  "Seals",
  "Seasonings or Spices and Condiments",
  "Seat Cushions",
  "Seats-Folding",
  "Seeded Paper",
  "Seeds",
  "Self-adhesive Products",
  "Sewing Kits and Accessories",
  "Shakers",
  "Shavers",
  "Shaving Kits",
  "Sheet Protectors",
  "Shelves",
  "Shirts",
  "Shirts - Men's",
  "Shirts - Women's",
  "Shoe Accessories",
  "Shoe Laces",
  "Shoe Shine Kits",
  "Shoehorns",
  "Shoes",
  "Shopping Accessories",
  "Shorts",
  "Shot Glasses",
  "Shovels",
  "Shredders",
  "Signs and Displays",
  "Silly Putty",
  "Single-sheet Calendar Products",
  "Skateboards",
  "Skewers",
  "Skin-care Products",
  "Skirts",
  "Sleeping Bags",
  "Slicers",
  "Slide Charts / Wheels",
  "Slides",
  "Slippers",
  "Smoked Meats and Fish",
  "Smoking Accessories",
  "Snacks",
  "Snow Globes",
  "Snowboards",
  "Soap Accessories",
  "Soap and Shampoo",
  "Soccer Accessories",
  "Socks",
  "Solar Accessories",
  "Souvenirs",
  "Spa Accessories",
  "Spas",
  "Speakers",
  "Special Event Accessories",
  "Special Packaging",
  "Specials",
  "Specialties",
  "Sponges",
  "Spoons",
  "Sport Bags",
  "Sports Bottles",
  "Sports Equipment and Accessories",
  "Sports Novelties",
  "Sports Schedules",
  "Sports and Recreation Footwear",
  "Squeegees",
  "Stadium Accessories",
  "Stadium Cups",
  "Stainless Steel Products",
  "Stamp Accessories",
  "Stamp Pads / Ink",
  "Staple Removers",
  "Staplers",
  "Stationery/Business Forms",
  "Statues",
  "Steak Accessories",
  "Steamers",
  "Steins",
  "Stemware",
  "Stencils",
  "Stereo Equipment",
  "Stick-on Attachment",
  "Stickers",
  "Stirrers and Sticks-Drink",
  "Stockings",
  "Stones",
  "Stoppers",
  "Stopwatches",
  "Straps",
  "Straws",
  "Streamers",
  "Stress Relievers and Cards",
  "Stress Toys",
  "Strobe Lights",
  "Styluses",
  "Suggestion Boxes",
  "Suitcases and Luggage",
  "Sunglasses and Accessories",
  "Sunscreen",
  "Sunshades",
  "Suntan Lotion",
  "Surfboards",
  "Survival Accessories",
  "Suspenders",
  "Sweat Clothes and Accessories",
  "Sweatbands",
  "Sweaters",
  "Sweatshirts",
  "Swim Accessories",
  "Swim Fins",
  "Swimming Pool",
  "Swimsuits",
  "T-Shirts",
  "Table Numbers",
  "Table Runners",
  "Tablecloths and Tablecloth Sets",
  "Tables",
  "Tablet Accessories",
  "Tags",
  "Tape",
  "Tape Measures",
  "Tapes and Accessories",
  "Tassels",
  "Tattoos",
  "Tea",
  "Team Items",
  "Teapots",
  "Technical Equipment",
  "Technology Products",
  "Telephones",
  "Telescopes",
  "Tennis Accessories",
  "Tennis Balls",
  "Tents",
  "Test Tubes",
  "Thermal Products",
  "Thermometers",
  "Thermos",
  "Throws",
  "Tickets",
  "Tie Tack Jewelry",
  "Ties and Accessories",
  "Tiles",
  "Timers",
  "Tins",
  "Tissue Covers",
  "Tissues",
  "Toasters",
  "Toilet Seats / Products",
  "Toiletries",
  "Tokens and Medallions",
  "Tool Boxes",
  "Tool Kits",
  "Tools",
  "Toothbrushes and Toothpaste",
  "Toothpicks and Accessories",
  "Tops and Spinners",
  "Towels",
  "Toys",
  "Trade Show Accessories",
  "Trash Cans",
  "Travel Accessories",
  "Travel Incentives",
  "Trays",
  "Treasure Chest Promotions",
  "Trees",
  "Trivet",
  "Trophies",
  "Tumblers",
  "Tweezers",
  "USB Drive",
  "Umbrellas",
  "Underwear",
  "Uniforms/Work Wear",
  "Utensils",
  "Utility Products",
  "Vacuum Cleaners",
  "Vases",
  "Vests",
  "Video Products",
  "Videos",
  "Vinyl Plastic Specialties",
  "Virtual Reality",
  "Visors",
  "Volleyball and Accessories",
  "Wagons",
  "Walking Accessories",
  "Wall Calendars",
  "Wall Clocks",
  "Wall Hangings",
  "Wall Poster Frames",
  "Wall and Door Nameplates",
  "Wallet Cards",
  "Wallets",
  "Warmers",
  "Wastebaskets",
  "Watch Accessories",
  "Watch Bands and Straps",
  "Watches",
  "Water",
  "Water Bottles",
  "Water Glasses",
  "Water Guns",
  "Waterproof Accessories",
  "Weather Accessories",
  "Weather Instruments",
  "Websites",
  "Wedding Accessories",
  "Weekly Calendar Products",
  "Weights",
  "Western Accessories",
  "Whistles",
  "Wind Chimes",
  "Window Accessories",
  "Windshield Accessories",
  "Wine Accessories",
  "Wine Glasses",
  "Wine Openers",
  "Wines",
  "Wipers",
  "Wood Nickels",
  "Wood Pens",
  "Wood Specialties-Custom Made",
  "Woven Shirts",
  "Wrapping Paper",
  "Wrist Accessories",
  "Wristbands",
  "Writing Accessories",
  "Yard Accessories",
  "Yardsticks",
  "Years of Service Awards",
  "Yo-Yo's",
  "Zipper Pullers"
]

created_seeds = 0
monkey_categories.each do |cat_name|
  taxon = Spree::Taxon.find_or_create_by!(name: cat_name, taxonomy: categories_taxonomy) do |t|
    t.parent = categories_root
  end
  created_seeds += 1
end
puts "Successfully seeded #{created_seeds} categories under taxonomy 'Categories'!"
